"""Outcome-free source admission and analyte-specific measurement contract."""
import json


def add(P):
    r=json.load(open('results/resistant_starch_metadata_census_corrected_20261007.json'))
    P.h('A larger resistant-starch deposit does not yet pass cohort admission')
    P.p('The measured yogurt/oats result motivates a larger human intervention source, but changing the diet and assay changes the scientific task. We inspected the primary resistant-starch reports by Baxter and colleagues (mBio 2019, https://journals.asm.org/doi/10.1128/mbio.02566-18) and Venkataraman and colleagues (Microbiome 2016, https://pmc.ncbi.nlm.nih.gov/articles/PMC4928258/). The published effect descriptions were visible during source discovery; neither source is an untouched outcome holdout. Baxter reports 174 young adults sampled across four University of Michigan academic semesters, with resistant potato starch, resistant maize starch, inulin or accessible-starch control groups. Participants continued their habitual diets. Three or four stools were collected before supplementation and three or four in the full-dose third week, separated by an unsampled 4-7 day dose transition. This parallel supplement design is not a replication of the yogurt crossover horizon, and its principal acetate, propionate and butyrate measurements plus a total are not eight independent chemical outcomes.')
    P.p('The public deposit is linked explicitly in the publication as SRP128128, including SCFA metadata. Live ENA accession inventory maps it to PRJNA428736, with 1,205 sequencing runs and 1,201 distinct samples. Before inspecting schemas we froze a metadata-only admission protocol, then a bounded three-specimen spotcheck chosen by sorted accession rather than phenotype. The official ENA/INSDC policy permits unrestricted access, analysis and publication of public records with original-submission credit (https://www.ebi.ac.uk/ena/browser/about/policies). That policy supplies a public-record research route, not a license for unrelated author files or commercial clearance. No participant-level rows are redistributed by this work. The XML response inevitably contains deposited chemical values, but this admission process discards them and retains only aggregate presence and finite-numeric parseability flags. It does not evaluate effect sizes, prognosis or forecast error.')
    P.p('A separately frozen full census made one bounded request. The initial project-browser endpoint returned a 1,968-byte PROJECT record rather than linked sample records; this was an endpoint-selection error, not an empty cohort. We retained that failure and made no automatic retry. After consulting official advanced-search documentation, a separately approved corrected request to the sample-search endpoint returned 6,123,886 bytes in 37.854 seconds, inside the 20-megabyte and 60-second limits. Both SAMPLE-element count and unique sample-accession count were asserted against the prior 1,201-sample inventory before any census metrics were reported. The corrected export had no duplicate sample accessions. Raw XML remained in process memory and was not saved; subject labels were used only for within-process grouping and were excluded from aggregate output.')
    P.table(['Evidence layer','Observed aggregate','What it does not establish'],[
        ['Public sample inventory','1,201 samples / 1,205 runs','Independent subjects or assay eligibility'],
        ['Source subject keys','175, with both phases represented','Publication population of 174'],
        ['At least 3 specimens in each phase','143 subject keys','3 valid measurements for each analyte'],
        ['Phase metadata','601 before / 600 during','Exact causal treatment horizon'],
        ['Within-subject arm or semester conflict','0 / 0','Independent recruitment across papers'],
        ['Missing required metadata fields','0','Complete numerical chemical panel'],
    ],'Outcome-free resistant-starch census; specimen, subject-key and published-participant counts are different evidence layers.')
    P.p('The census contains four nonempty arm labels and four semester labels spanning 2015-2017. Every subject key has at least one specimen in each phase, and no key crosses an arm or semester. This structural completeness is useful for building a future paired design, but it does not reconcile the deposit with the publication. A literal minimum-three-specimens-per-phase count yields 143 keys, whereas the report describes 174 analyzed participants and exclusion for fewer than three samples collected or successfully analyzed before or during supplementation. Possible assay-specific coverage, sequencing exclusions, key semantics or differences between public and analyzed samples are explanations to investigate, not facts established here. We do not delete one of the 175 keys, relax the specimen minimum, or reinterpret missingness to reproduce a preferred participant count.')
    P.table(['Attribute','Present specimens','Finite numeric parseability','Not counted as finite'],[
        [a,r['outcome_present_counts'][a],r['outcome_numeric_parseable_counts'][a],1201-r['outcome_numeric_parseable_counts'][a]]
        for a in ['acetate','propionate','butyrate','total SCFA']
    ],'Presence and parser acceptance, not concentrations or biological differences. Non-finite or non-numeric entries are not assigned a scientific meaning by this audit.')
    # Keep this short table together so a wrapped header is never split across pages.
    for row in P.doc.tables[-1].rows[:-1]:
        for cell in row.cells:
            for para in cell.paragraphs:
                para.paragraph_format.keep_with_next = True
                para.paragraph_format.keep_together = True
    P.p('All four chemical attributes appear in every sample record, but numeric coverage differs. An attribute may exist while its value is a missing-assay code, censoring notation, non-finite token or another source-specific representation. The census does not infer which explanation applies and does not impute values. Consequently, a complete sample-to-subject join cannot certify a complete measured panel. Nor can a count of finite values establish comparable calibration. Baxter reports HPLC concentrations normalized to each specimen wet weight, in mmol/kg wet feces. The earlier Venkataraman study uses the average collected fecal mass of 0.67 g for normalization. Combining those concentrations without a measurement contract would silently substitute different calibration assumptions.')
    P.p('The earlier study provides a second warning about dataset independence. Its accession SRP067761 maps to PRJNA306884, with 157 public samples. First, middle and last accession schemas expose collection dates but no explicit subject, supplement, before/during or SCFA attributes; their collection years are 2015. Both publications recruit from University of Michigan BIO173 and cite HUM00094242. Baxter includes fall-2015 specimens. Distinct accession IDs and publications therefore do not prove distinct recruitment, and calendar years alone do not exclude overlap. We retain one unresolved source family rather than count these as independent laboratories or replications. A future semester-held-out analysis would be a within-source temporal check, even if subjects were disjoint. An independent biological test requires separate source evidence, not a more favorable split label.')
    P.h('An analyte-specific panel gate separates presence from admissibility')
    P.p('The source census motivated an offline platform component rather than an immediate fit. The chemical-panel gate consumes a closed schema: sample identifier, source family, subject identifier, arm, before/during phase, finite numeric collection time and one explicit observed boolean per requested analyte. Raw concentration fields are rejected. A caller must establish the source meaning of missing and sentinel values before converting them to observed flags, and must separately verify units, assay, calibration and rights. This division prevents a generic parser from transforming a string that happens to be numeric into a scientifically valid measurement. Unit verification must be an explicit boolean; an unverified unit produces abstention, even when sufficient observed flags are present.')
    P.p('The grouping key is source family plus subject, while specimen identity is scoped by source. Identical subject labels in different sources are not merged. Within a source-subject group, conflicting arms block eligibility. Baseline specimens must precede every during-phase specimen; if the last baseline time is at or beyond the first during time, the group is blocked rather than silently sorted into a usable forecast. Duplicate specimen IDs or source-subject-time coordinates are rejected because unresolved technical replicates cannot become extra biological observations. These checks do not infer time units, exposure start dates, washout, or treatment adherence. They operate only on a source-grounded schema supplied by the caller.')
    P.p('The frozen default requires at least three observed specimens before and during for each analyte. The function reports each analyte eligible-subject count, the number of subjects meeting the rule for every analyte, and a stricter complete-specimen-panel count. These targets differ. A subject may have enough acetate observations and enough butyrate observations on partially different stools, yet not have three stools per phase on which both are measured. The joint analyte count is appropriate for separate analyte summaries only when that interpretation is fixed beforehand. A model needing simultaneous chemical vectors must use the stricter same-specimen panel count or an explicitly justified missing-data design. Neither count authorizes imputation or retrospective selection of whichever panel produces a better score.')
    P.p('Sixteen new offline fixtures cover complete panels, analyte-specific missingness, the joint-versus-same-specimen distinction, source-key collisions, temporal leakage, arm conflicts, duplicate specimens and times, unsupported phases, raw values, malformed flags and unverified units. Negative fixtures remain part of the contract. Four separate census-parser fixtures check that outcome values and subject identifiers do not enter output, non-finite values are not counted as finite, PROJECT responses cannot become empty-cohort summaries, and duplicate accessions fail reconciliation. The full suite after this unit has 467 passed tests, one skipped test and one existing LightGBM warning. The source endpoint was not called again to test the refactor. This is software reliability evidence, not confirmation of eligibility or a scientific win.')
    P.p('Implementation and evidence are in src/microtwin/chemical_panel_admission.py, scripts/resistant_starch_metadata_census.py, results/RESISTANT_STARCH_SOURCE_ADMISSION_20261007.md and the associated aggregate census JSON. The function is a library component, not a hosted service or new clinical workflow. Admission remains pending: reconcile the analysis population, establish analyte-specific missingness semantics and calibration, audit exact specimen lineage, then freeze the task and comparisons before reading outcomes for fitting. No raw-read reprocessing, model training, perturbation scoring or larger-cohort power claim was performed. This route adds a concrete biological measurement gate to the platform while leaving the independent benchmark, replicated discovery and useful predictive-win requirements unchanged.')
