"""Separate relative composition prediction from absolute direction feasibility."""
import json


def add(P):
    r=json.load(open('results/load_direction_grid_20261007.json'))
    P.h('Relative composition accuracy does not identify absolute response direction')
    P.p('The chemical-panel admission contract addresses whether an observed metabolite is usable for a fixed task. A different measurement boundary concerns the taxonomic response itself. Composition accuracy can be high while the absolute direction of a taxon remains unknown. Write its compatible true relative fraction as p and its total community load as T. Absolute abundance is p times T. Between baseline and a later sample, its absolute fold is the relative-fraction fold multiplied by the total-load ratio. This identity does not use fitted interactions, and prediction of a relative fraction does not supply the missing scale. Sequencing-library size is not a substitute for microbial load. A causal intervention forecast requires more evidence still: knowing the absolute direction of an observed change does not identify its cause.')
    P.p('This limitation is established rather than a new biological discovery. Vandeputte and colleagues describe quantitative microbiome profiling combining amplicon sequencing and flow-cytometric cell enumeration, and explain that relative microbiome profiles alone cannot reveal the extent or direction of absolute changes (Nature 2017, https://www.nature.com/articles/nature24460 ; indexed abstract https://pubmed.ncbi.nlm.nih.gov/29143816/). Their reported load variation motivates measuring scale rather than assuming constancy. Their workflow also distinguishes copy-number-corrected profiles from raw read fractions and notes different biases in cell enumeration and molecular qPCR. We therefore do not treat an amplicon fraction times an arbitrary load estimate as an independently validated cell count. Taxon definition, extraction, measurement material, calibration and load units must first be compatible.')
    P.p('We implement a narrow feasibility check under declared interval constraints. The true baseline fraction is supplied in a positive interval [bL,bU], the true later fraction in [dL,dU], and the load ratio in [qL,qU]. Fractions must be at most one and all endpoints strictly positive, finite and ordered. The Cartesian-box assumption allows each value to vary independently within its interval. The smallest feasible absolute fold is dL times qL divided by bU; the largest is dU times qU divided by bL. These are interval extrema, not a posterior or a confidence interval. If the measurements have joint constraints, some corners of this box may be impossible, and the caller must supply or justify those dependencies instead of presenting the simple box as exact biology.')
    P.equation('F_abs = (p_during / p_before) (T_during / T_before);   F_abs in [dL qL / bU, dU qU / bL]')
    P.p('A lower bound strictly above one supports an increase only under the submitted measurement box. An upper bound strictly below one supports a decrease under that box. A lower bound below one and upper bound above one supplies two explicit opposite-direction feasibility witnesses. A bound touching one, or the singleton one, cannot certify a strict sign and returns abstention. Unknown total-load ratio or unverified measurement compatibility also returns abstention. The function rejects zero fractions rather than adding a pseudocount: a below-detection observation needs a detection-limit and measurement-error model before a meaningful fold can be bounded. This strict separation avoids manufacturing an absolute response from an absence code.')
    P.table(['Before fraction','During fraction','Load ratio interval','Absolute fold interval','Result'],[
        ['0.1','0.2','[0.25, 4]','[0.5, 8]','Opposite directions feasible'],
        ['0.1','0.2','[0.9, 1.1]','[1.8, 2.2]','Increase under supplied box'],
        ['0.1','0.2','[0.5, 1]','[1, 2]','Boundary abstention'],
        ['[0.08, 0.12]','[0.16, 0.24]','[0.4, 0.6]','[0.533333, 1.8]','Opposite directions feasible'],
    ],'Synthetic scale-interval witnesses, not measured taxon responses. The same relative increase can be compatible with both absolute directions when total load is sufficiently uncertain.')
    for row in P.doc.tables[-1].rows[:-1]:
        for cell in row.cells:
            for para in cell.paragraphs:
                para.paragraph_format.keep_with_next=True
                para.paragraph_format.keep_together=True
    P.p('The doubled relative fraction is a useful concrete contrast. Before p=0.1 and after p=0.2, a load ratio of 0.25 gives an absolute fold of 0.5, while a ratio of four gives a fold of eight. Both satisfy the same exact composition change and the broad declared load box. A tight ratio of 0.9-1.1 excludes the decrease and restricts the fold to 1.8-2.2. Neither example is a measured intervention or a probability assigned to either endpoint. The information that changes the conclusion is the load constraint, not a new ecological model. Similarly, uncertainty in both fractions and the load can cross the no-change boundary even if the supplied later-fraction interval lies entirely above the baseline interval.')
    counts={s:sum(c['status']==s for c in r['cells']) for s in {c['status'] for c in r['cells']}}
    P.p('The protocol froze eleven deterministic cells before execution: three exact later fractions, 0.05, 0.1 and 0.2, each crossed with three load-ratio intervals, plus one uncertain-fraction cell and one boundary-touching cell. All eight corners of every supplied box were enumerated to check the analytic extrema, with maximum disagreement at most 1e-12. The grid retains two increase-under-box results, two decreases, five opposite-direction witnesses and two boundary abstentions. Runtime was approximately 0.000276 seconds; there was no sampling, optimization, biological dataset or model training. All eleven outcomes remain in results/load_direction_grid_20261007.json, and useful_win=False. This is an algebraic implementation check, not a predictive benchmark or measured calibration result.')
    P.p('Fifteen offline fixtures cover the grid, both sign witnesses, tight-load conclusions, unknown load, unverified measurement compatibility, boundary touching, unordered or non-finite bounds, Boolean-as-number mistakes and zero-fraction rejection. The standalone execution script initially failed to import the local source package before running any cells; an explicit source-path import fixed execution without changing the scientific grid. The implementation is src/microtwin/load_direction.py with scripts/load_direction_grid.py and the frozen protocol results/PREREG_20261007_load_direction.md. Its output explicitly denies independent validation, causal interpretation and clinical eligibility. It is a library function rather than a hosted platform endpoint.')
    P.p('This direction check and the earlier gLV removal witness answer different questions. The load box asks whether an observed relative change can be translated into an absolute change under measurement constraints. The gLV witness asks whether models consistent with a synthetic equilibrium can disagree about an unobserved species-removal response. Measuring total load can reduce the first ambiguity without identifying interaction parameters or resolving the second. Conversely, a fitted dynamic model cannot repair an incompatible measurement scale by asserting a confident intervention sign. A future multimodal twin should record absolute load, chemical measurements and taxon fractions as separate evidence layers, with their calibration and specimen linkage checked before joint fitting. No current result here demonstrates that integration or a replicated ecological discovery.')
