"""Measured October 7 metabolite task and source-admission methods."""
import json


def add(P):
    r = json.load(open('results/scfa_first_period_forecast_20261007.json'))
    e = r['evaluation']
    P.h('Measured extension: first-period stool-metabolite forecasting')
    P.p('A personalized research platform needs a task with measurable targets, known sample units and an honest boundary around what its model predicts. The next measured extension therefore uses targeted stool short-chain fatty acid (SCFA) concentrations rather than borrowing an unverified taxonomic table or treating predicted gene functions as observed biology. The public 2026 yogurt and rolled-oats crossover study supplies an explicitly CC BY 4.0 metabolite deposit, Zenodo record 15363886. Its eight analytes are 2-methylbutyric acid, acetic acid, butyric acid, hexanoic acid, isobutyric acid, isovaleric acid, propionic acid and valeric acid, measured in micrograms per gram of stool. This is a different measurement contract from relative microbial abundance: concentrations are not normalized to sum to one, and predicting them does not certify taxonomic composition, causal ecological interactions or clinical benefit.')
    P.p('The original trial randomized 119 adults; 110 completed all four phases. Each participant consumed 250 grams of yogurt daily in one four-week intervention and the same yogurt plus 50 grams of rolled oats daily in another. Treatment order was randomized, with four-week washout phases. The deposit contains 462 samples, of which 440 are main samples and 22 are quality-control duplicates. All main samples form unique submitted subject-time coordinates across four phases. The analysis deliberately uses only the first baseline and first post-intervention sample. It does not learn from the second intervention, pool repeated periods as independent people or assume that washout eliminated carryover. Group A receives yogurt first and group B receives yogurt plus oats first. The model sees that intervention label, but the task remains a forecast in observed treated participants, not an estimate of what the same person would have experienced without treatment.')
    P.p('Metadata inspection preceded any concentration scoring. This order found an important difference between nominal phase labels and actual collection dates. First-period intervals range from 24 to 138 days in the deposited metadata, while later washout intervals include two nonpositive values and some date endpoints do not parse. These entries were not silently repaired. The frozen first-period task retains only baseline-to-follow-up intervals of 21 through 35 days, inclusive. This bounds collection separation without pretending that dietary start, adherence or exact exposure duration were measured by the sample label. The result cannot support a continuous-time kinetic model or a clinical scheduling recommendation. Public scripts elsewhere in the author repository include illustrative participant clinical records; those records are neither model features nor public outputs of this analysis.')
    P.p('The concentration workbook has 3,696 unique sample-analyte records, exactly eight for each of its 462 sample labels, and those labels match the metabolite metadata. Units and material are uniform. The local reproduction script verifies the original workbook MD5 and metadata SHA-256 before processing. Primary assay eligibility is strict: all baseline and target cells must be finite nonnegative numbers, within their stated lower and upper quantitation limits, and free of nonempty analysis comments. The laboratory report says that values outside calibration range may be extrapolated and flagged BLOQ or ALOQ. The analysis does not convert those flags to zero, remove an inconvenient metabolite, or impute a favorable response. Complete-case filtering leaves 84 subjects, 42 in each treatment-order group. Twenty-five subjects fail the assay rule and one fails the collection interval. This restriction is material: the estimates apply to quantifiable complete cases, not all randomized participants or all low-concentration specimens.')
    P.p('A frozen five-fold subject split holds out entire submitted people. Within each arm, sorted subject labels are shuffled with a fixed random seed and assigned cyclically to folds. Log1p baseline concentrations are standardized using training-fold statistics. A ridge model with fixed alpha 10 predicts change in log concentration from eight baseline features, the assigned first intervention, and eight baseline-by-intervention products. Predicted target log concentrations are clipped only below zero; there is no compositional projection. No hyperparameter search, effect-based feature selection or alternate model variant follows the score. The comparators are persistence, training-only same-arm mean log change, and the mean change of the three nearest same-arm baseline donors. Neighbors are selected in training-standardized baseline space. This is a demanding practical comparison because a personalized predictor must add value over carrying the last measurement forward or borrowing an observed donor response.')
    P.p('The primary error averages absolute log concentration errors across analytes after scaling by each target-log training-fold standard deviation, then averages over held-out subjects. Scaling prevents a large natural range in one analyte from dominating every other target; it does not create a universal reliability score. Secondary results retain unscaled log errors and per-analyte errors. The useful-win rule was frozen before outcome inspection: at least ten percent lower primary error than each comparator, with a negative upper bound on each paired subject-bootstrap interval. The bootstrap uses 2,000 subject resamples and is descriptive within this study. It does not establish independent-source replication, correct for all previous development choices or supply calibrated patient-level prediction intervals.')
    rows = [[k, e['models'][k]['primary_mean_error'], e['models'][k]['unscaled_mean_absolute_log_error']]
            for k in ('ridge','persistence','arm_mean','nearest_three')]
    P.table(['Forecast', 'Standardized log error', 'Unscaled log error'], rows,
            'First-period SCFA held-subject development forecasts, 84 complete-case subjects; smaller error is better.')
    P.p('The fixed ridge forecast has primary mean error 0.702517, compared with 0.798983 for persistence, 0.806896 for same-arm mean change and 0.775684 for nearest-three donors. Relative improvements are 12.07, 12.94 and 9.43 percent. The corresponding paired model-minus-reference bootstrap intervals are [-0.169426, -0.022469], [-0.172099, -0.034693] and [-0.123910, -0.020608]. Thus the model improves the aggregate metric against all three fixed baselines in this development evaluation, but the third improvement falls below the required ten percent. The recorded verdict is useful_win=False. This distinction matters: a favorable direction of error change does not satisfy a preregistered usefulness rule. The threshold is not lowered to rescue the result, and a close miss is not promoted to a win against a leading external tool.')
    P.p('Aggregate accuracy also hides target-specific weaknesses. Hexanoic acid has mean absolute log error 0.690508 under ridge, worse than persistence at 0.601259. A user should not infer that every metabolite benefits from the aggregate improvement. All eligible subjects are scored once, predictions are finite, and replacing held-out targets leaves their predictions unchanged. The mandatory replacement check refits the five folds for verification, giving ten small fits in total: five scoring fits and five verification fits. This exceeds the brief five-fit execution estimate but stays inside the frozen single-thread, 120-second evaluation limit; measured evaluation time is 0.287 seconds. No extra scientific variant or paid compute was used. These checks establish local execution properties, not true biological identity or generalization to a new laboratory.')
    P.h('Source admission is part of the measurement, not a dataset count')
    P.p('Several apparently suitable antibiotic cohorts did not supply the full evidence needed for a comparable task. CEREMI has multiple publications and accessions from the same trial, not independent replication. Hagan has a well-defined antibiotic course and a primary deposit, but this bounded inventory inspection did not retrieve a taxonomic table with an exact phase, subject and collection-time join. Raymond has clear cefprozil dosing and untreated controls, yet its inspected supplements contain quality-control and statistical tables rather than an identified complete abundance matrix. Its final sample label denotes ninety days after treatment end, so treating that label as ninety days after first dose would alter the time axis. Zaura provides an important further warning: the primary study selected its shotgun pairs for the largest observed microbiome changes. Such a selected subset cannot be an unbiased multimodal validation sample merely because two assays exist.')
    P.p('Palleja illustrates why processed-data availability alone is insufficient. Its author archive is retrievable and its primary sample table has 57 specimens from twelve donors. An educational mirror has 57 abundance-table headers, but eight primary sample IDs carry an opt suffix absent from the mirror. The analysis does not strip the suffix and assert provenance. The earlier clinical report also describes stool collected before named visits and an additional antibiotic course in one participant. The bounded author archive contains more than one gigabyte of uncompressed tables and no README, license or sample-map member in its inspected inventory. The approved extraction stop was honored. This is not proof that the source is unusable forever; it is a precisely described admission gap. A later MISO diet deposit similarly uses an other-open label without explicit reuse terms in the inspected archive. Its seven-day homogeneous diet and measured outputs cannot be substituted for four-week yogurt/oat SCFA validation without a separate task contract.')
    P.p('The licensed SCFA route therefore adds a small, reproducible quantitative test and exposes a modest predictive signal, while leaving the larger scientific promises open. Its concentrations are now viewed development data, not an untouched holdout. The taxonomic GitHub tables stay metadata-only because the article license and metabolite-deposit license do not automatically establish their own reuse scope. Neither the source hunt nor the SCFA forecast closes independent top-tool benchmarking, causal perturbation validation, replicated keystone discovery, foundation-scale training or external calibration. The appropriate next scientific question is whether a locked transferable task works in an independently recruited, measurement-compatible and explicitly reusable cohort. If those requirements fail, the platform should abstain rather than accumulate nominal datasets or relabel a same-study result as discovery.')
