"""Separate analytic-reference simulation under explicit normal assumptions."""
import json


def add(P):
    r=json.load(open('results/hierarchical_reference_20261007.json'))
    P.h('An analytic reference isolates the interval approximation')
    P.p('The first simulation leaves an important question open: preserving subject grouping does not make a small-sample percentile interval well calibrated. We therefore froze a separate follow-up after seeing that result, with a fresh seed and a narrower null-only grid. It is a development-directed methodological check, not an untouched confirmation. The same normal equal-repeat construction implies independent normal subject means with variance rho plus (one minus rho) divided by the repeat count. Under that explicit model, the standard Student-t interval for the subject-mean population mean is an analytic reference. It estimates variability from the submitted subject means, uses sample standard deviation with n minus one degrees of freedom, and has half-width equal to the 97.5th t percentile times that deviation divided by the square root of n. This established formula is documented by NIST, https://www.itl.nist.gov/div898/handbook/eda/section3/eda352.htm ; quantiles are computed by SciPy 1.14.1, https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html .')
    P.p('We also compute an oracle normal interval whose variance is known from the generative construction. Its half-width is the 97.5th standard-normal percentile times the square root of [rho+(1-rho)/repeats]/n. The oracle is a diagnostic reference, not an available real-data competitor: a microbiome analyst generally does not know the true covariance or population variance. Comparing it with the estimated-variance t interval separates information supplied by the construction from information estimated from the sample. Both analytic intervals target the same mean as the cluster percentile interval; none fits a microbiome model or predicts an intervention.')
    P.p('The frozen grid has subject counts 4, 5, 10 and 20, repeats 1 and 25, correlations 0, 0.5 and 0.9, and true mean zero throughout: 24 cells. Each cell has 500 independent panels and each cluster interval uses 199 bootstrap draws. The seed is 20261008, separate from the first experiment. Coverage, positive lower-endpoint exclusion, width and Monte Carlo standard error are retained for all cells. Across this grid, cluster coverage ranges from 0.774 to 0.942, Student-t coverage from 0.932 to 0.968, and oracle coverage from 0.936 to 0.962. Positive null exclusion ranges from 0.020 to 0.112 for cluster percentiles, 0.010 to 0.036 for t intervals and 0.014 to 0.034 for the oracle. These finite Monte Carlo ranges are observations, not exact probability bounds.')
    rows=[]
    for n in [4,5,10,20]:
        x=next(x for x in r['cells'] if (x['subjects'],x['repeats'],x['rho'])==(n,25,.9))
        rows.append([n]+[x[k]['coverage'] for k in ['cluster','student_t','known_variance_oracle']]+[x[k]['mean_width'] for k in ['cluster','student_t','known_variance_oracle']])
    P.table(['Subjects','Cluster coverage','t coverage','Oracle coverage','Cluster width','t width','Oracle width'],rows,'Separate null-only normal-model reference, 25 repeats and correlation 0.9; 500 panels per cell. Oracle variance is known by construction, not estimated or available in the biological platform.')
    P.p('With four subjects in this high-correlation slice, cluster coverage is 0.774 and average width 1.452. The t interval has coverage 0.952 and width 2.818; the oracle has coverage 0.948 and width 1.864. Wider uncertainty under a defensible distributional assumption is not an algorithmic failure merely because a narrow interval appears more useful. With five subjects, observed t coverage is 0.932 rather than 0.95, and that negative deviation remains in the table. At ten subjects the three coverages are 0.916, 0.958 and 0.956; at twenty they are 0.942, 0.966 and 0.960. The construction provides an analytic reason to expect nominal t coverage over repeated sampling, but 500 panels do not force every realized proportion to equal that nominal value.')
    P.p('The interpretation is narrow. An approximate cluster percentile interval can under-cover with few independent normal subjects, even when the grouping is correct. An established t interval addresses that approximation under the normal independent-mean assumption, while its broader validity in actual compositional, heavy-tailed, unequally sampled or model-fitted microbiome errors remains untested. The oracle illustrates the variance information problem rather than solving it. This is not a new uncertainty method, a clinically calibrated score, a distribution-free guarantee, a study-design power recommendation or a biological discovery. It cannot retrofit the archived mouse comparisons into independent replication.')
    P.p('The separate run completed 12,000 panels and 36,000 intervals in 4.688 seconds inside the same single-thread 120-second and 256-megabyte limits. Its protocol and executable code were committed before these outcomes. The first 72-cell artifact is unchanged. All 24 follow-up cells are in results/hierarchical_reference_20261007.json; protocol results/PREREG_20261007_hierarchical_reference.md and script scripts/hierarchical_reference.py define the assumptions and formulas. The recorded useful_win=False keeps this established-method reference separate from the requested biological benchmark and discovery gates. Future real-data uncertainty work would have to justify the subject-error distribution or evaluate suitable alternatives prospectively, rather than choose the interval that makes an already viewed result significant.')
