"""Frozen synthetic precision experiment, no biological fit."""
import json


def add(P):
    r=json.load(open('results/hierarchical_precision_20261007.json'))
    P.h('Synthetic precision test: repeated rows are not new subjects')
    P.p('The biological-unit concern can be tested quantitatively without opening a new biological outcome. We froze a synthetic experiment in which the true mean paired loss gap is known. For independent subject i and repeated observation j, the gap is delta plus a shared standard-normal subject term weighted by the square root of rho and an independent standard-normal observation term weighted by the square root of one minus rho. Thus rho is the within-subject correlation and each individual observation has variance one. The target is the equally weighted mean subject gap. The grid contains four subject counts (4, 5, 10 and 20), three repeat counts (1, 10 and 25), three correlations (0, 0.5 and 0.9), and two true gaps (0 and 0.25), giving 72 cells. All choices were frozen before computation; repeat count was bounded to 25 rather than the initial planning concept of 100.')
    P.p('Each cell has 100 independent Monte Carlo panels. For each panel we compute two percentile bootstrap intervals with 199 resamples and the default linear 2.5 and 97.5 percentiles. Naive resampling treats all subject-by-repeat observations as independent rows. Cluster resampling first averages within each subject and resamples those subject means. Bootstrap random draws are separate for the two methods. Coverage means that the interval contains the known true delta; a strictly positive lower endpoint is counted separately. Under delta zero that positive exclusion is a one-sided false-positive diagnostic, not the entire two-sided error rate. Under delta 0.25 it is a detection rate for this constructed model, not a real-cohort power estimate. Mean interval width and coverage Monte Carlo standard error are retained for every cell.')
    rows=[]
    for n in [4,5,10,20]:
        x=next(x for x in r['cells'] if (x['subjects'],x['repeats'],x['rho'],x['true_gap'])==(n,25,.9,0))
        rows.append([n,x['naive']['coverage'],x['cluster']['coverage'],x['naive']['positive_exclusion_rate'],x['cluster']['positive_exclusion_rate'],x['naive']['mean_width'],x['cluster']['mean_width']])
    P.table(['Subjects','Naive coverage','Cluster coverage','Naive positive exclusion','Cluster positive exclusion','Naive width','Cluster width'],rows,'Frozen synthetic null at 25 repeats and correlation 0.9. Each rate is based on 100 panels. Width is in synthetic paired-gap units, not microbiome abundance. This selected slice is illustrative; all 72 cells are retained in the result artifact.')
    P.p('In that high-correlation slice, naive coverage stays between 0.27 and 0.32 despite nominal 0.95 intervals. Cluster coverage is 0.81, 0.87, 0.87 and 0.90 as subject count rises from four to twenty. Naive positive exclusion rates range from 0.24 to 0.35; cluster rates range from 0.03 to 0.12. Cluster intervals are wider because they preserve the shared subject component instead of treating repeated rows as new independent information. This result demonstrates a precision failure in the constructed correlated-row setting. It does not establish that cluster resampling has achieved nominal coverage or that twenty subjects suffice for a microbiome trial.')
    P.p('The negative controls prevent a universal claim about bootstrap superiority. At zero correlation with 25 repeats and four subjects, naive coverage is 1.00 in these 100 panels while cluster coverage is 0.84; with five subjects the values are 0.89 and 0.81. Independent repeated errors supply real additional information in this special model, while a small collection of subject averages makes the percentile bootstrap vulnerable to its finite-sample approximation. Across the complete null grid, cluster coverage ranges from 0.74 to 0.98; across the positive-gap grid it ranges from 0.72 to 0.96. The variation, and the small Monte Carlo count, prohibit treating a single cell as an exact coverage guarantee. A reported Monte Carlo standard error of zero at an observed rate of zero or one is only the plug-in estimate, not proof that the underlying event probability is exactly zero or one.')
    P.p('This experiment also has a simple variance interpretation. Under the declared equal-repeat normal model, the sample mean variance is rho/n plus (1-rho)/(n times repeats). At zero correlation, repeats reduce both components to independent observation noise. At positive correlation, increasing repeats cannot eliminate the shared subject term rho/n. Increasing independent subjects reduces that term; adding more taxon-time rows within the same subject does not. This identity follows from the construction, not from a fitted microbiome covariance model. In real compositional or longitudinal data, unequal repeats, missingness, treatment allocation, model fitting, heavy tails and source shifts can alter both the relevant target and the uncertainty calculation.')
    P.p('The run processed 7,200 panels and 14,400 intervals in 2.977 seconds under a 120-second single-thread local cap. No biological input, training outcome or new model fit was used. The frozen protocol and code were committed before scoring. Complete results are results/hierarchical_precision_20261007.json, protocol results/PREREG_20261007_hierarchical_precision.md, and script scripts/hierarchical_precision.py. The recorded useful_win=False reflects that this is a methodological sensitivity study, not a biological benchmark. Neither resampling method is new, and the result does not establish priority, a universal minimum sample size or replicated ecological discovery. It gives a concrete reason to retain biological-unit grouping while separately testing whether the chosen small-sample interval method is adequate.')
